### ISSUE TITLE
Inconsistency - Keyed Lists

### ISSUE THREAD

**Issue by ryansolid** [platformatic/ssr-performance-showdown#16]
There is one more inconsistency here and I want to see if anyone has an opinion on it. It is important because the cost of serializing the row id is actually substantial in this benchmark. I'm not suggesting this for Solid's sake either since we encode a hydration ID that no one else does which costs us here regardless.

But for the sake of being consistent I think all frameworks should use their keyed lists if applicable. Current all implementations do except Svelte unless Svelte 5 now works like Solid and keys by reference (can you clarify @Rich-Harris?). For these frameworks using a key is a diffing overhead but doesn't impact serialization. The key is not sent to the client in the form of an attribute.

Additionally I suggest that non-hydrating implementations remove the key attribute such as (fastify-html, htmx) as they are paying a penalty for it that the others don't since their framework keys aren't serialized. In the end only Solid gets punished for the extra attribute but I'm ok with that because that is how our solution works(related to JSX being created out of order and not having keys).

**Comment by Rich-Harris** [comment]
In Svelte, keys must be explicit (we don't automatically key by reference because there's no way to know that the list doesn't contain duplicates, though we _may_ in a future version make keyed the default with an opt-out for the cases where it's necessary), but they are disregarded for SSR purposes — if there's a discrepancy on hydration, we repair rather than move: 

<img width="939" alt="image" src="https://github.com/user-attachments/assets/e7d7c1f0-9b46-4a7c-8362-86219cd2630e">

**Comment by ryansolid** [comment]
Alright then I move that to make all the implementations their equivalent the best we can we merge #17.
